name: Download Purpur

on:
  workflow_dispatch:

permissions:
  contents: write   # ðŸ‘ˆ Ø£Ù‡Ù… Ø®Ø·ÙˆØ©

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x scripts/download_purpur.sh

      - name: Run download script
        run: ./scripts/download_purpur.sh

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Purpur jar to latest version"
