name: Run Purpur Download Script

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x scripts/download_purpur.sh

      - name: Run download script
        run: ./scripts/download_purpur.sh

      - name: Commit and push downloaded file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add server/purpur.jar
          git commit -m "Downloaded purpur.jar automatically"
          git push
